apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-minikube
  namespace: jfrog-project
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
spec:
  rules:
    - host: jfrog.artifactory
      http:
        paths:
          - path: /unsecured(/|$)(.*)
            backend:
              serviceName: expose-ngix
              servicePort: 80

