apiVersion: v1
kind: Service
metadata:
  name: expose-ngix
  namespace: jfrog-project
spec:
  selector:
    app: artifactory
    component: nginx
    release: artifactory
  ports:
    - name: nginxhttp
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: NodePort