apiVersion: v1
kind: Pod
metadata:
  labels:
    app-name: pipeline-pods
spec:
  containers:
    - name: maven
      image: maven:alpine
      volumeMounts:
        - name: jenkins-pvc
          mountPath: /root/.m2
      command:
        - cat
      tty: true
    - name: docker
      image: docker:18.09-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
    - name: kubectl
      image: gcr.io/cloud-builders/kubectl
      command:
        - cat
      tty: true
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: jenkins-pvc
      persistentVolumeClaim:
        claimName: myclaim
