apiVersion: v1
kind: Pod
metadata:
  labels:
    app-name: pipeline-pods
spec:
  containers:
    - name: maven
      image: maven:alpine
      command:
        - cat
      tty: true
    - name: docker
      image: docker
      command:
        - cat
      tty: true
    - name: kubectl
      image: gcr.io/cloud-builders/kubectl
      command:
        - cat
      tty: true
