apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins-project
spec:
  selector:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins
  ports:
    - name: jenkinshttp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30112
  type: NodePort