
# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

## Overrides for generated resource names
# See templates/_helpers.tpl
# nameOverride:
# fullnameOverride:

master:
  nodePort: 32000
  # List of plugins to be install during Jenkins master start
  installPlugins:
    - kubernetes:1.15.4
    - workflow-job:2.32
    - workflow-aggregator:2.6
    - credentials-binding:1.18
    - git:3.10.0
  cpu: "1"
  memory: "3500Mi"
  javaOpts: "-Xms3500m -Xmx3500m"


agent:
  enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock

persistence:
  size: 20Gi

networkPolicy:
  apiVersion: networking.k8s.io/v1

## Install Default RBAC roles and bindings
rbac:
  serviceAccount:
    name: default
