kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kubernetes-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: backend
        app: backend
        env: dev
    spec:
      containers:
      - name: backend
        image: rjain236/webserver:1.2.0-SNAPSHOT
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
